### ISSUE TITLE
error when passing `concat_ngrams=False`

### ISSUE THREAD

**Issue by yiyixuxu** [lucidrains/n-grammer-pytorch#2]
in this assert statement, the condition inside `not(...)` is actually the required condition

```python
assert not (not concat_ngrams and dim_per_head == ngram_emb_dim), 'unigram head dimension must be equal to ngram embedding dimension if not concatting'
```

https://github.com/lucidrains/n-grammer-pytorch/blob/main/n_grammer_pytorch/n_grammer_pytorch.py#L149

**Comment by lucidrains** [comment]
@yiyixuxu thanks for catching this!
