### ISSUE TITLE
missing `repeat` function

### ISSUE THREAD

**Issue by SirRob1997** [lucidrains/n-grammer-pytorch#3]
Where does `repeat` in [this line](https://github.com/lucidrains/n-grammer-pytorch/blob/df514e05aeb713a139ccc1e42bea9b6e6c3f825f/n_grammer_pytorch/n_grammer_pytorch.py#L176) come from? I'm guessing there is an import missing from `einops`.

**Comment by lucidrains** [comment]
@SirRob1997 oh yes, thank you!
